const USER_LOGIN = 'USER_LOGIN';
const USER_SIGNUP_SUBMIT = 'USER_SIGNUP_SUBMIT';
const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';

export const actionTypes = {
    USER_LOGIN,
    USER_SIGNUP_SUBMIT,
    USER_SIGNUP_SUCCESS,
    USER_SIGNUP_ERROR
};
