const USER_SIGNUP_SUBMIT = 'USER_SIGNUP_SUBMIT';
const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';
const USER_SIGNUP_CANCEL = 'USER_SIGNUP_CANCEL';

const USER_LOGIN_SUBMIT = 'USER_LOGIN_SUBMIT';
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
const USER_LOGIN_CANCEL = 'USER_LOGIN_CANCEL';

const FETCH_NOTES_REQUEST = 'FETCH_NOTES_REQUEST';
const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
const FETCH_NOTES_CANCEL = 'FETCH_NOTES_CANCEL';
const FETCH_NOTES_ERROR = 'FETCH_NOTES_ERROR';

export default {
    USER_SIGNUP_SUBMIT,
    USER_SIGNUP_SUCCESS,
    USER_SIGNUP_ERROR,
    USER_SIGNUP_CANCEL,
    USER_LOGIN_SUBMIT,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_ERROR,
    USER_LOGIN_CANCEL,
    FETCH_NOTES_REQUEST,
    FETCH_NOTES_SUCCESS,
    FETCH_NOTES_CANCEL,
    FETCH_NOTES_ERROR
};
